server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://${spring.cloud.client.ip-address}:8080/eureka
  instance:
    hostname: ${spring.cloud.client.ip-address}
spring:
  application:
    name: usersCenter