server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://${spring.cloud.client.ip-address}:8080/eureka
  instance:
    hostname: ${spring.cloud.client.ip-address}
spring:
  application:
    name: usersCenter
  datasource:
    druid:
      username: root
      password: root
      url: jdbc:mysql://localhost/example?useSSL=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
      driver-class-name: com.mysql.cj.jdbc.Driver
